<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	
	<artifactId>entity-solr</artifactId>
	<name>Europeana Entity Collection - Solr index management </name>
	<organization>
		<name>Europeana Foundation + AIT</name>
	</organization>
	<url>http://www.europeanalabs.eu</url>
	<parent>
		<artifactId>entity-api</artifactId>
		<groupId>eu.europeana.entity</groupId>
		<version>2.4</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>

	<dependencies>
		<dependency>
			<groupId>eu.europeana.entity</groupId>
			<artifactId>entity-common</artifactId>
			<version>2.4</version>
		</dependency>

		<dependency>
			<groupId>eu.europeana.entity</groupId>
			<artifactId>entity-definitions</artifactId>
			<version>2.4</version>
		</dependency>

		<dependency>
			<groupId>jakarta.annotation</groupId>
			<artifactId>jakarta.annotation-api</artifactId>
			<version>${jakarta.annotation.version}</version>
		</dependency>

		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>${jackson.version}</version>
			<scope>compile</scope>
		</dependency>
		
		<dependency>
			<groupId>org.apache.solr</groupId>
			<artifactId>solr-solrj</artifactId>
			<version>${version.apacheSolr}</version>
			<exclusions>
				<exclusion>
					<artifactId>wstx-asl</artifactId>
					<groupId>org.codehaus.woodstox</groupId>
				</exclusion>
				<exclusion>
					<groupId>com.fasterxml.woodstox</groupId>
					<artifactId>woodstox-core</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<dependency>
			<groupId>eu.europeana.api</groupId>
			<artifactId>commons-sb3-search</artifactId>
			<version>${version.commons.api.sb3}</version>
			<exclusions>
			<exclusion>
			<groupId>org.apache.solr</groupId>
			<artifactId>solr-solrj</artifactId>
			</exclusion>
			</exclusions>
		</dependency>
		
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-context</artifactId>
		</dependency>
		
		<!-- Other -->
		<!-- Test dependencies -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>org.junit.vintage</groupId>
					<artifactId>junit-vintage-engine</artifactId>
				</exclusion>
				<exclusion>
					<groupId>com.vaadin.external.google</groupId>
					<artifactId>android-json</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-logging</artifactId>
				</exclusion>
				<exclusion>
					<groupId>jakarta.annotation</groupId>
					<artifactId>jakarta.annotation-api</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<scope>test</scope>
			<groupId>org.springframework</groupId>
			<artifactId>spring-test</artifactId>
		</dependency>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-api</artifactId>
			<scope>test</scope>
		</dependency>
        		
	</dependencies>
	
</project>
