
#Spring configs
spring.application.name=Entity API v2
spring.main.allow-bean-definition-overriding=false
info.app.name=${spring.application.name}
info.app.version=${project.version}
info.app.description=Europeana Entity API v2

# Enable http2
server.http2.enabled=true
server.error.include-message=always
server.error.include-stacktrace=on_param
server.error.include-exception=false
server.error.see-also=https://pro.europeana.eu/page/apis
server.port=8080


management.info.env.enabled=true
management.endpoints.web.exposure.include=health,info
# for debugging conditioonal annotations locally the following configuration can be used
management.info.build.enabled=true
management.info.git.enabled=true
management.health.probes.enabled=true