<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<artifactId>entity-api</artifactId>
		<groupId>eu.europeana.entity</groupId>
		<version>2.5.1-SNAPSHOT</version>
	</parent>

	<artifactId>entity-definitions</artifactId>
	<name>Europeana Entity Collection - Definitions</name>
	<organization>
		<name>Europeana Foundation + AIT</name>
	</organization>
	
	<dependencies>
		
		<dependency>
			<groupId>eu.europeana.api</groupId>
			<artifactId>commons-sb3-definitions</artifactId>
			<version>${version.commons.api.sb3}</version>
		</dependency>
		
		<!-- Other -->
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
		</dependency>
	</dependencies>
</project>
