apiVersion: apps/v1
kind: Deployment
metadata:
  name: entity-api-v2-deployment
spec:
  # selector.matchLabels is provided via Kustomize
  template:
    spec:
      containers:
        - name: entity-api-v2
          image: europeana/entity-api-v2
          env: 
            - name: SPRING_CONFIG_NAME
              value: "application,entity,entity.user"
            - name: SPRING_CONFIG_ADDITIONAL_LOCATION
              value: "/opt/app/config/entity.user.properties"
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/liveness
              httpHeaders:
                - name: Accept
                  value: application/json
            initialDelaySeconds: 40
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/readiness
              httpHeaders:
                - name: Accept
                  value: application/json
            initialDelaySeconds: 40
          volumeMounts:
            - name: secret
              mountPath: "/opt/app/config/entity.user.properties"
              readOnly: true
              subPath: entity.user.properties
            - name: log4j-config
              mountPath: "/opt/app/config/log4j2-spring.xml"
              readOnly: true
              subPath: log4j2-spring.xml  
      volumes:
        - name: secret
          secret:
            secretName: entity-api-props
        - name: log4j-config
          configMap:
            name: log4j2-properties    