apiVersion: apps/v1
kind: Deployment
metadata:
  name: entity-api-v2-deployment
spec:
  # selector.matchLabels is provided via Kustomize
  template:
    spec:
      containers:
        - name: entity-api-v2
          image: europeana/entity-api-v2
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/liveness
            initialDelaySeconds: 40
            periodSeconds: 20
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/readiness
            initialDelaySeconds: 40
            periodSeconds: 20
          volumeMounts:
            - name: secret
              mountPath: "/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/entity.properties"
              readOnly: true
              subPath: entity.properties
      volumes:
        - name: secret
          secret:
            secretName: entity-api-v2-secret