resources:
  - deployment.yaml

labels:
  - includeSelectors: true
    pairs:
      app: entity-api-v2

# expects files to be in the same directory
secretGenerator:
  - name: entity-api-v2-secret
    files:
      - entity.properties